kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: onify-agent-test
  namespace: onify-test
spec:
  host: onify-agent-test.it.helsinki.fi
  to:
    kind: Service
    name: agent-server
    weight: 100
  port:
    targetPort: agent-server-http
  tls:
    termination: edge
    certificate: |
      -----BEGIN CERTIFICATE-----
        insert
      -----END CERTIFICATE-----
    key: |
      -----BEGIN PRIVATE KEY-----
        insert
      -----END PRIVATE KEY-----
    caCertificate: |
      -----BEGIN CERTIFICATE-----
        insert
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
        insert
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      insert
      -----END CERTIFICATE-----
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
