apiVersion: apps/v1
kind: Deployment
metadata:
  name: onify-app
  labels:
    app: onify
    tier: app
spec:
  selector:
    matchLabels:
      app: onify
      tier: app
  template:
    metadata:
      labels:
        app: onify
        tier: app
    spec:
      imagePullSecrets:
      - name: onify-regcred
      containers:
      - name: app
        image: eu.gcr.io/onify-images/hub/app:2.7.3
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1000Mi"
            cpu: "500m"
          limits:
            memory: "2000Mi"
            cpu: "2"
        envFrom:
        - configMapRef:
            name: onify-app-config
        env:
        - name: ONIFY_api_admintoken
          valueFrom:
           secretKeyRef:
             name: onify-app-secrets
             key: api_token
        - name: ONIFY_disableAdminEndpoints
          value: "false"
        ports:
        - name: app
          containerPort: 3000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 25%