apiVersion: apps/v1
kind: Deployment
metadata:
  name: onify-app
  labels:
    app: onify
    tier: app
spec:
  selector:
    matchLabels:
      app: onify
      tier: app
  template:
    metadata:
      labels:
        app: onify
        tier: app
    spec:
      imagePullSecrets:
      - name: onify-regcred
      containers:
      - name: app
        image: eu.gcr.io/onify-images/hub/app:2
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1000Mi"
            cpu: "500m"
          limits:
            memory: "2000Mi"
            cpu: "2"
        env:
        - name: ONIFY_API_TOKEN
          valueFrom:
           secretKeyRef:
             name: onify-app-secrets
             key: api_token
        - name: ONIFY_API_URL_INTERNAL
          value: http://onify-api:8181/api/v2
        - name: ONIFY_API_URL_EXTERNAL
          value: https://onify-api.it.helsinki.fi/api/v2
        ports:
        - name: app
          containerPort: 3000