kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: onify-ext
  namespace: onify
spec:
  host: onify-ext.it.helsinki.fi
  to:
    kind: Service
    name: onify-app
    weight: 100
  port:
    targetPort: onify-app
  tls:
    termination: edge
    certificate: |-
      -----BEGIN CERTIFICATE-----
      insert
      -----END CERTIFICATE-----
    key: |-
      -----BEGIN PRIVATE KEY-----
      insert
      -----END PRIVATE KEY-----
    caCertificate: |-
      -----BEGIN CERTIFICATE-----
      insert
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      insert
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      insert
      -----END CERTIFICATE-----
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None