apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: onify
    tier: persistance
    service: elasticsearch
spec:
  ports:
  - port: 9200
    name: client
  - port: 9300
    name: nodes
  selector:
    app: onify
    tier: persistance
    service: elasticsearch