kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: onify-elasticsearch-pvc
spec:
    storageClassName: pomppa25
    resources:
        requests:
            storage: 10Gi
    accessModes:
    - ReadWriteOnce