kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: onify-resources-pvc
spec:
  storageClassName: pomppa25
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce