kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: onify-api
  namespace: onify-int
spec:
  host: onify-api.it.helsinki.fi
  to:
    kind: Service
    name: onify-api
    weight: 100
  port:
    targetPort: onify-api-443
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None