kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: onify-api
  namespace: onify-int
spec:
  host: onify-api.it.helsinki.fi
  to:
    kind: Service
    name: onify-api
    weight: 100
  port:
    targetPort: onify-api-443
  tls:
    termination: edge
    certificate: |
      -----BEGIN CERTIFICATE----
       < insert value >
      -----END CERTIFICATE-----
    key: |
      -----BEGIN PRIVATE KEY-----
       < insert value >
      -----END PRIVATE KEY-----
    caCertificate: |
      -----BEGIN CERTIFICATE-----
      < insert value >
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
       < insert value >
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
       < insert value >
      -----END CERTIFICATE-----
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None